language: ruby

services:
 - postgresql

rvm:
  - 2.6.2

cache: bundler

before_install:
  - gem update --system
  - bundle install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - rspec
  - rubocop
