language: ruby
cache: bundler
install: gem install bundler:1.3.0
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
before_script:
  - bundle install
  - bundle exec rake db:setup
script:
  - bundle exec rubocop
  - bundle exec rspec
